### PR TITLE
Uniform init of SD's radii and positions

### PR DESCRIPTION
**Pull request by pdziekan**
Replace sd_conc_mean with sd_conc - each cell gets exactly sd_conc SDs.

In each cell, radii of SDs are not chosen completely randomly, but are more evenly distributed on the whole range.

### CODE REVIEW

**Comment by pdziekan** [comment]
Incorporated the new rd_min/max search used by master into this pull request.

**Comment by slayoo** [comment]
Just sent an e-mail to Shin-ichiro to consult if they had any thoughts on that.

**Comment by pdziekan** [comment]
Anyone willing to look through it now?
I've ran a lot of simulations using this pull request and they all worked fine. 
Also, it doesn't slow down the simulation (it only affects initialization).

**Comment by trontrytel** [comment]
Why does it fail travis checks? - Did you look into it? - From what I see it fails not only because of the parcel model. 

I propose maybe to disable checks with libcloudph and parcel on travis and see what else needs to be done for this pull to pass all tests. (We could do the same for other hanging pull requests from libcloudph). Afetr that I'll fix errors with parcel model.

I will be at work on Monday afternoon and can do it then

**Comment by pdziekan** [comment]
When compiled with clang, it only fails on parcel (as it uses sd_conc_mean and the oull req changes that to sd_conc).

When compiled with gcc, it also fails when compiling icicle, most probably because the compiler runs out of memory or it takes too long to process the CUDA version of the library, which is not compiled on the clang machines. Same thing happened for some previous pull requests.

The best solution would be get more memory/faster machine/more computer time on the gcc machine. Ofc we could disable parcel and icicle and it would pass test just fine :)

**Comment by pdziekan** [comment]
update: it's not timeout, since it is killed after approx 1min, so it's probably memory issue.
From documentation:
"
My build script is killed without any error #
...
- g++ needing too much memory to compile files, for instance with a lot of templates included.
  "

**Comment by slayoo** [comment]
What about making the uniform/nonuniform initialisation an option?
This would make it possible:
- to reproduce the results from libcloudphxx paper without needing to downgrade the library
- to exemplify how the uniform initialisation differs from the one originally used in SDM

S.

**Comment by pdziekan** [comment]
Imho there is no way nonuniform init is superior and I don't think we need to always be able to exactly reproduce results of that paper. Still there is always the RNG in play and with uniform init you obtain results as good as with other RNG seed.

Anyway, being able to compare with original SDM is a good thing, so I can add this uniform/nonuniform init option. I'd just rather do that after (or together with) next pull req in line, which deals with sources of aerosol. That is because it will introduce some changes in init, thanks to which init will be reused when applying source.

**Pull request merged**
