### PR TITLE
Terminal velocity selection [includes sg_surf -> sg_surf(T); coal_switch]

### PR DESCRIPTION
**Pull request by pdziekan**
Added the Beard formula, which is now selected by default.

### CODE REVIEW

**Comment by slayoo** [comment]
Let's wait for 1.0.0 release before merging it - just to keep the 1.0 documentation in the paper consistent with the code.

**Comment by slayoo** [comment]
Perhaps it's better to require the user to chose it manually?
Otherwise, the behaviour will change from 1.0.0 without any notice.

**Comment by pdziekan** [comment]
Good point, updated the request accordingly.

**Comment by pdziekan** [comment]
Created a drops.py pull request to match the new API. Should be merged together with this one.

**Comment by pdziekan** [comment]
Just wrote a mail to authors of the kappa-Kohler theory asking about the temperature/surface tension we should use.

**Comment by pdziekan** [comment]
I received an answer from Markus Petters:

"For prediction of sc, it is correct to use the actual temperature. In addition, I would recommend to also include the temperature dependence of surface tension. In practice the effect is quite large and it is important to account for it. I am attaching a more recent paper where we explicitly addressed the role of temperature via experimentation (J. Phys. Chem. A 2012, 116, 9706−9717). "

**Comment by slayoo** [comment]
Thanks!

Here's an update to drops.py, that will make it not complain: https://github.com/igfuw/drops.py/pull/56

And here's a PR to the branch proposed here which fixes conflicts with current master (and merges the current master in): https://github.com/pdziekan/libcloudphxx/pull/6

Let's merge this one after merging both of the above and receiving OK from Travis.

S.

**Pull request merged**
