### PR TITLE
Icicle relaxation: set norhs if not relaxing; correct relaxation formula

### PR DESCRIPTION
**Pull request by pdziekan**

### CODE REVIEW

**Comment by slayoo** [comment]
:( this seems more tricky as the VOCALS set-up defines the relaxation in terms of initial liquid water potential temperature, and not the potential temperature...

**Comment by slayoo** [comment]
then, perhaps recording the th_d and rv field just after spin-up would make sense?

**Comment by pdziekan** [comment]
Ok, now relaxing towards profile averaged over x after spinup.
There is still the problem (?) that, due to the flow, th and rv are not uniform in x right after spinup.

**Comment by pdziekan** [comment]
tested relaxation - seems to work fine

**Pull request merged**
