### PR TITLE
hskpng_Tpr: if const_p, assume that th is theta_std

### PR DESCRIPTION
**Pull request by pdziekan**

### CODE REVIEW

**Comment by trontrytel** [comment]
Why do we need double precision in v_term calculations?

**Comment by pdziekan** [comment]
We need doubles there, because with floats it sometimes gave nans on CUDA.

**Comment by trontrytel** [comment]
Sometime ago we talked about potentially switching from the SI units to units better suited for the microphysics scales. I think boost.unis does provide a way of using a different scale? Would it help if our default length unit was micro meter and not a meter? I think the trend is to move to single precision not the other way ;)

**Comment by pdziekan** [comment]
It might help, but I wouldn't bet on it.

Critical radius calculation is also done with doubles.
I tested rescaling radius to microns and calculating critical radius with floats and it didn't work.
It did work with floats when fast_math wasn't used in CUDA, but the slowdown was much bigger than one caused by using doubles. Can't remember which specific fast_math flag was responsible.

**Pull request merged**
