### PR TITLE
dylib vs so

### PR DESCRIPTION
**Pull request by trontrytel**
I don't know if thats the way to fix it. But my osx creates .dylib and cmake was only looking for .so file for the lagrangian part of our library.

### CODE REVIEW

**Comment by pdziekan** [comment]
Probably would be better to set libcloudphxx_LIBRARY_DIR and then the extension would not have to be specified.

**Comment by trontrytel** [comment]
I can do this in **libcloudph++-config.cmake** file:
>set(libcloudphxx_LIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}/../../lib/")

But then how should I combine it with the **CMakeLists.txt** we have for the models that use _libcloudph++_ ? For example in libcloudphxx/models/kinematic_2D/src/CMakeLists.txt, but also in UWLCM?

Right now we have: 
> target_link_libraries(icicle ${libcloudphxx_LIBRARIES})

I tried something like:
>link_directories(${libcloudphxx_LIBRARY_DIR})
>target_link_libraries(icicle libcloudphxx_lgrngn)

But **link_directories** is depreciated by cmake. And it didn't work anyhow.

**Comment by pdziekan** [comment]
It seems that direct link paths (and not directories) are the way to do it, sorry for confusion.
Please throw away the commented code with LIBRARY_DIR and feel free to merge yourself.

**Comment by trontrytel** [comment]
done!

**Pull request merged**
